# Generated by Django 4.0.2 on 2022-04-01 18:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_eligible', models.BooleanField(default=False)),
                ('program_name', models.TextField()),
                ('currency', models.TextField()),
                ('country_name', models.TextField()),
                ('bank_name', models.TextField()),
            ],
        ),
    ]
