# Generated by Django 4.0.2 on 2022-04-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='bank_id',
            field=models.OneToOneField(db_column='bank', default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='banks.bank'),
        ),
    ]
